### ISSUE TITLE
Accordion failing on IE 10

### ISSUE THREAD

**Issue by kyort** [aut0poietic/ali#16]
IE 10 is returning this error.

SCRIPT5007: Unable to get value of the property 'aria': object is null or undefined 
ali.min.js, line 8 character 5708

This is the line it references:

$el.aria({role:"tablist",multiselectable:"true"})

**Comment by aut0poietic** [comment]
Babel's es6 -> es5 inheritance is not compatible with IE10. As IE10 is a project requirement, I'll be refactoring ali to use js, not es6.

This bug will serve as the capstone to that refactor.

:disappointed:

**Comment by aut0poietic** [comment]
confirmed fixed with a724dd2e63fc39dd10e7dede1f80966fd78c93fa
