### ISSUE TITLE
Accordion interaction breaks in IE 10

### ISSUE THREAD

**Issue by EbizSean** [aut0poietic/ali#32]
http://aut0poietic.github.io/ali/accordion.html

When using IE 11 and switching to IE 10 emulator, the page containing the Accordion interaction becomes unresponsive. The error code that is given states, "Line: 1
Error: Object doesn't support property or method 'matches'."

**Comment by aut0poietic** [comment]
Please re-test. This may be a flaw in either your testing methods or in prism.js -- which may have been patched by removing a plugin.

Need verification before I can continue

**Comment by EbizSean** [comment]
Related #33

**Comment by aut0poietic** [comment]
Fixed. Object.assign() replaced with jQuery.extend() for cloning of event objects.
