### ISSUE TITLE
Multiple Choice doesn't work in IE

### ISSUE THREAD

**Issue by EbizSean** [aut0poietic/ali#33]
http://aut0poietic.github.io/ali/multiple-choice.html

In IE 11, the answers are not selectable by mouse or keyboard (the distractors are in the tab order and visually highlight, but do not produce the checkmark and the question Submits as wrong). 

In IE 11 as IE10, I get the following error: 
"Object doesn't support property or method 'assign'."

**Comment by aut0poietic** [comment]
Interaction.prototype.itemSelected=function(a){var b=Object.assign({},this.data);

**Comment by aut0poietic** [comment]
FIXED. Note that IE10 has alignment issues. Acceptable as these will be replaced in any significant implementation.
