### ISSUE TITLE
Order items doesn't show in IE

### ISSUE THREAD

**Issue by EbizSean** [aut0poietic/ali#35]
http://aut0poietic.github.io/ali/order-items.html

In IE 11, only option #8 "Intimacy vs Isolation" shows up. This is also true in the IE 10 emulator.

**Comment by aut0poietic** [comment]
IE 10 appears to not be applying the -ms-transform styles -- it's completely missing from trace styles.

**Comment by EbizSean** [comment]
I have verified that all options show up and work in IE 11 and IE 11 as 10.
