### ISSUE TITLE
Answer set does not work in IE 10

### ISSUE THREAD

**Issue by EbizSean** [aut0poietic/ali#36]
http://aut0poietic.github.io/ali/answer-set.html

When I try to answer the questions in IE11 as IE10, I get an error that states "Object doesn't support property or method 'assign'."

**Comment by aut0poietic** [comment]
Related to #33 ; 

Seems to be a flaw in the Interaction class.

**Comment by aut0poietic** [comment]
Fixed. Object.assign() replaced with jQuery.extend() for cloning of event objects.
