### ISSUE TITLE
Order Elements

### ISSUE THREAD

**Issue by aut0poietic** [aut0poietic/ali#9]
Users are displayed a list of elements to order. Each element has a numbered drop-down and the user selects the order for that element and  the element animates to the appropriate place in the order, reordering any other elements. 

- 3 to 8 elements per interaction
- Interaction is evaluated on submit.
- Contains correct/incorrect feedback
- On submit, the elements can optionally reorder themselves to show the correct order.

**Comment by kyort** [comment]
you probably want to include some specifications as to the length of each element

**Comment by aut0poietic** [comment]
It's still early, but I'm thinking I'll equalize the size of each element.

So long as the elements aren't completely obnoxious in length, they should be fine.
